/// Flutter icons GaneshaIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  GaneshaIcons
///      fonts:
///       - asset: fonts/GaneshaIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class GaneshaIcons {
  GaneshaIcons._();

  static const _kFontFam = 'GaneshaIcons';
  static const String? _kFontPkg = null;

  static const IconData aiComment = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData aiRecommend = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attach = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData voice = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sendMessage = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
